name: lastchaos

services:
  mysql:
    image: mariadb:10.4.19
    container_name: lc_mysql
    environment:
      #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      TZ: America/Sao_Paulo
    volumes:
      - ./server/db/mysql:/var/lib/mysql
      # - ./server/db/scripts/:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - lastchaos_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --event-scheduler=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1  --net-read-timeout=120 --net-write-timeout=120
    restart: unless-stopped
  lc_server:
    build:
      context: .
      dockerfile: Dockerfile.centos
    container_name: lc_server
    stdin_open: true
    tty: true
    volumes:
      - ./server:/lastchaos/server/
      - ./server_run:/lastchaos/server_run/
    ports:
    - "4001:4001"   # LoginServer
    - "4101:4101"   # GameServer
    networks:
      - lastchaos_network
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    command:
      [
        "/bin/bash",
        "-c",
        "chmod -R 777 /lastchaos && cd /lastchaos && python server_run/python/serverstart.py && tail -f /dev/null",
      ]

networks:
  lastchaos_network:
    driver: bridge
