FROM centos:7

# Configurar repositórios manualmente
RUN cd /etc/yum.repos.d/ \
    && sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*


RUN yum -y update && yum -y install epel-release && yum clean all


RUN yum -y install ld-linux.so.2 libaprutil-1.so.0 libstdc++.so.6 libz.so.1 libldap-2.4.so.2 mono-complete gdb screen --setopt=protected_multilib=false && yum clean all



RUN yum install -y epel-release && \
    yum install -y MySQL-python && \
    yum install -y mysql && \
    yum install -y net-tools && \
    yum clean all

COPY ./Libs/* /usr/lib/


RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    echo "America/Sao_Paulo" > /etc/timezone


WORKDIR /lastchaos

# Fix Windows CRLF line endings in shell scripts (breaks #!/bin/bash shebang)
COPY ./server_run/fix_crlf.sh /usr/local/bin/fix_crlf.sh
RUN chmod +x /usr/local/bin/fix_crlf.sh