#!/bin/bash

while ( : ) do
        DATE=`date`
        if [ -r .shutdown ]; then
                rm -f .shutdown
        fi

        #cp ../../new/Connector_d .
        ./gdb --batch --command=cmd ./Connector_d > "bt_`date +%y%m%d%H%M%S`.log"

        DATE2=`date`
        if [ -r .shutdown ]; then
                echo "***** Shutdown $DATE ~ $DATE2" >> rebootlog
                exit
        fi

        echo "!!!!! Reboot $DATE ~ $DATE2" >> rebootlog
        sleep 2
done
